# -*- coding: utf-8 -*-
"""CIE  3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xictjItiZHvRhezgFg_xxwOrYVXNMc0
"""

import pandas as pd
df=pd.read_csv('/content/Housing.csv')

df.head()

df.describe()

df.info()

# data preprocessing
df.isnull().sum()

df.dropna()

#data spliting
from sklearn.model_selection import train_test_split
x=['area','parking','price']
y=['bedrooms','prefarea','basement']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("x train:",x_train)
print("x test:",x_test)
print("y train:",y_train)
print("y test:",y_test)

#data exploration
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.read_csv('/content/Iris.csv')
df.head()
df.describe()

#data preprocessing
df.isnull().sum()

df.dropna()

# data spliting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(test_size=0.2,random_state=42)
print("x train:",x_train)
print("x test:",x_test)
print("y train:",y_train)
print("y test:",y_test)